<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Design an A/B Test</title>

<script src="udacity-dand-p7-design-an-a-b-test_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="udacity-dand-p7-design-an-a-b-test_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="udacity-dand-p7-design-an-a-b-test_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="udacity-dand-p7-design-an-a-b-test_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="udacity-dand-p7-design-an-a-b-test_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="udacity-dand-p7-design-an-a-b-test_files/navigation-1.1/tabsets.js"></script>
<link href="udacity-dand-p7-design-an-a-b-test_files/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="udacity-dand-p7-design-an-a-b-test_files/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Design an A/B Test</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#introduction"><span class="toc-section-number">1</span> Introduction</a></li>
<li><a href="#experiment-design"><span class="toc-section-number">2</span> Experiment Design</a><ul>
<li><a href="#metric-choice"><span class="toc-section-number">2.1</span> Metric Choice</a></li>
<li><a href="#measuring-standard-deviation"><span class="toc-section-number">2.2</span> Measuring Standard Deviation</a></li>
</ul></li>
</ul>
</div>

<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>At the time of this experiment, Udacity courses currently have two options on the course overview page: “start free trial”, and “access course materials”. If the student clicks “start free trial”, they will be asked to enter their credit card information, and then they will be enrolled in a free trial for the paid version of the course. After 14 days, they will automatically be charged unless they cancel first. If the student clicks “access course materials”, they will be able to view the videos and take the quizzes for free, but they will not receive coaching support or a verified certificate, and they will not submit their final project for feedback.</p>
<p>In the experiment, Udacity tested a change where if the student clicked “start free trial”, they were asked how much time they had available to devote to the course. If the student indicated 5 or more hours per week, they would be taken through the checkout process as usual. If they indicated fewer than 5 hours per week, a message would appear indicating that Udacity courses usually require a greater time commitment for successful completion, and suggesting that the student might like to access the course materials for free. At this point, the student would have the option to continue enrolling in the free trial, or access the course materials for free instead. <a href="https://www.google.com/url?q=https://drive.google.com/a/knowlabs.com/file/d/0ByAfiG8HpNUMakVrS0s4cGN2TjQ/view?usp%3Dsharing&amp;sa=D&amp;ust=1505462930089000&amp;usg=AFQjCNHbTwpTCPD-bpNwBgyNz8Exgzif1A">This screenshot</a> shows what the experiment looks like.</p>
<p>The hypothesis was that this might set clearer expectations for students upfront, thus reducing the number of frustrated students who left the free trial because they didn’t have enough time—without significantly reducing the number of students to continue past the free trial and eventually complete the course. If this hypothesis held true, Udacity could improve the overall student experience and improve coaches’ capacity to support students who are likely to complete the course.</p>
<p>The unit of diversion is a cookie, although if the student enrolls in the free trial, they are tracked by user-id from that point forward. The same user-id cannot enroll in the free trial twice. For users that do not enroll, their user-id is not tracked in the experiment, even if they were signed in when they visited the course overview page.</p>
</div>
<div id="experiment-design" class="section level1">
<h1><span class="header-section-number">2</span> Experiment Design</h1>
<div id="metric-choice" class="section level2">
<h2><span class="header-section-number">2.1</span> Metric Choice</h2>
<p><strong>Invariant Metrics</strong>:</p>
<ul>
<li><strong>Number of cookies</strong>: The number of unique cookies to view the course overview page (# cookies) should be an invariant metric. This step happens before the free trial screener step. Therefore, the number of cookies should not change across the experiment group and the control group.</li>
<li><strong>Number of clicks</strong>: The number of unique cookies to click the “Start free trial” button (# clicks) should be an invariant metric. This step happens before the free trial screener step. Therefore, the number of clicks should not change across the experiment group and the control group.</li>
<li><strong>Click-through-probability</strong>: The number of unique cookies to click the “Start free trial” button (# clicks) divided by number of unique cookies to view the course overview page (# cookies) should be an invariant metric. Because both the numerator (# clicks) and the denominator (# cookies) do not change, the ratio (click-through-probability) should also not change across the experiment group and the control group.</li>
</ul>
<p><strong>Evaluation Metrics</strong>:</p>
<ul>
<li><strong>Gross conversion</strong>: The number of user-ids to complete checkout and enroll in the free trial (# user-ids) divided by number of unique cookies to click the “Start free trial” button (# clicks) should be an evaluation metric. The added time survey step should steer away users who do not have enough time for studying, and decrease the # trial user-ids. Because the numerator (# user-ids) should decrease and the denominator (# clicks) should be invariant, the ratio (gross conversion) should decrease for the experiment group.</li>
<li><strong>Net conversion</strong>: The number of user-ids to remain enrolled past the 14-day boundary (# remained user-ids) divided by the number of unique cookies to click the “Start free trial” button (# clicks) should be an evaluation metric. The numerator (# remained user-ids) is expected to be higher in experiment group as a result of increased overall experience, and the denominator (# clicks) should be invariant, therefore the ratio (net conversion) should be higher in the experiment group.</li>
</ul>
<p><strong>Metrics Not Chosen</strong>:</p>
<ul>
<li><strong>Number of user-ids</strong>: The number of users who enroll in the free trial (# user-ids) is not chosen as included metrics. Although # trial user-ids is expected to be reduced in the experiment group according to our hypothesis, we cannot guarantee that equal number of cookies are assigned into experiment and control group. This limitation makes the # trial user-ids less suitable to be used as an evaluation metric compared to a normalized metric such as gross conversion.</li>
<li><strong>Retention</strong>: The number of user-ids to remain enrolled past the 14-day boundary (# remained user-ids) divided by number of user-ids to complete checkout (# user-ids) was initially chosen as evaluation metrics. The retention is expected to be higher in the experiment group as a result of increased overall experience. However, after calculating the duration that needed for testing this metric, the duration is too long to be practical running this experiment. Therefore, retention is not chosen for the final experiment design.</li>
</ul>
<p>In order to launch the experiment, the experiment results need to align with the two goals:</p>
<ol style="list-style-type: decimal">
<li>Reduce the number of frustrated students who left the free trial because they didn’t have enough time.</li>
<li>Do not significantly reduce the number of students to continue past the free trial and eventually complete the course.</li>
</ol>
<p>These two goals correspond to the following two chosen evaluation metrics changes:</p>
<ol style="list-style-type: decimal">
<li>Decreased gross conversion.</li>
<li>Increase or non-changed net conversion.</li>
</ol>
<p>To launch the experiment, one should require to see <strong>BOTH</strong> decreased gross conversion <strong>AND</strong> increased or non-changed net conversion.</p>
</div>
<div id="measuring-standard-deviation" class="section level2">
<h2><span class="header-section-number">2.2</span> Measuring Standard Deviation</h2>
<p>Given a sample size of 5000 cookies visiting the course overview page</p>
<p>Rough estimates of the baseline values for these metrics:</p>
<table>
<thead>
<tr class="header">
<th>Metric Name</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Unique cookies to view course overview page per day</td>
<td>40000</td>
</tr>
<tr class="even">
<td>Unique cookies to click “Start free trial” per day</td>
<td>3200</td>
</tr>
<tr class="odd">
<td>Enrollments per day</td>
<td>660</td>
</tr>
<tr class="even">
<td>Click-through-probability on “Start free trial”</td>
<td>0.08</td>
</tr>
<tr class="odd">
<td>Probability of enrolling, given click</td>
<td>0.20625</td>
</tr>
<tr class="even">
<td>Probability of payment, given enroll</td>
<td>0.53</td>
</tr>
<tr class="odd">
<td>Probability of payment, given click</td>
<td>0.1093125</td>
</tr>
</tbody>
</table>
<pre class="r"><code>binomSD &lt;- function(p, n) {
  return(sqrt(p * (1-p) / n))
}</code></pre>
<pre class="r"><code># Number of clicks for the given sample
n_clicks = 5000 * (3200 / 40000)
# Gross conversion
p_gross_conversion = 0.20625
binomSD(p_gross_conversion, n_clicks)</code></pre>
<pre><code>## [1] 0.0202306</code></pre>
<p>Gross conversion standard deviation: 0.0202. The analytic estimate would be comparable to the empirical variability, because the unit of diversion and the unit of analysis are the same: a cookie.</p>
<pre class="r"><code># Net conversion
p_net_conversion = 0.1093125
binomSD(p_net_conversion, n_clicks)</code></pre>
<pre><code>## [1] 0.01560154</code></pre>
<p>Net conversion standard deviation: 0.0156. The analytic estimate would be comparable to the empirical variability, because the unit of diversion and the unit of analysis are the same: a cookie.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
